import MainLayout from "@/components/layout/main-layout";
import Providers from "@/providers";
import { merriweather } from "@/public/fonts";
import type { Metadata } from "next";
import "../components/styles/globals.css";

export const metadata: Metadata = {
  title: "MovieNest - Where Every Movie Has a Story",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${merriweather.className} antialiased`}>
        <Providers>
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );
}
